image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - dev
    - master
  script:
    - echo RUNNING TESTS
    - sudo apt-get install -y python-pip
    - pip install docker-compose
    - docker-compose -f docker-compose-pytest.yml up --build --abort-on-container-exit pytest
    - docker-compose -f docker-compose-pytest.yml down -v
  allow_failure: false

deploy:
  stage: deploy
  only:
    - master
  script:
    - sudo apt-get install -y python-pip
    - pip install docker-compose
    - docker-compose down
    - docker-compose up -d --build
  when: manual
  allow_failure: false
